### ISSUE TITLE
Change the dropdown option and transfer modal form style

### ISSUE THREAD

**Issue by hoonsubin** [PlasmNetwork/plasm-apps-vue#30]
# Task Summary

Currently, the style for a selected item vs an active item in the dropdown menu is not intuitive. We should fix this.

# Task List

- [ ] change the style for the active item in the `Choose Account` modal dropdown in the `Balance` page. The active item should have a highlighted background and the selected item should have a highlighted radio button https://github.com/PlasmNetwork/plasm-apps-vue/blob/c99b29f290bf2b3be6dd96a886fb112a0aa52a19/src/components/balance/ModalAccount.vue#L26
![only-highlight-active-item](https://user-images.githubusercontent.com/40356749/122744443-f1f84480-d2c2-11eb-89fd-620e4eaa8c3f.png)

- [ ] change the style for the active item in the `Choose Network` modal dropdown so that the current network has a highlighted background with a white text and the user-selected item has a light blue radio button https://github.com/PlasmNetwork/plasm-apps-vue/blob/c99b29f290bf2b3be6dd96a886fb112a0aa52a19/src/components/balance/ModalNetwork.vue#L22
![highlight-selected-network](https://user-images.githubusercontent.com/40356749/122744930-74810400-d2c3-11eb-8d5a-aa4200a8d282.png)

- [ ] highlight the hovering account in the `Transfer <Token>` modal and `Create Your dApps` account selection dropdown option and add a checkmark next to the current item
- [ ] disable the spell correction red underline for the account address input box in the `Transfer <Token> `modal account input and the `Create Your dApps` modal `Deployment Account` https://github.com/PlasmNetwork/plasm-apps-vue/blob/9d0538083fe77423370fdec5351de34e010047c4/src/components/balance/ModalSelectAccountOption.vue#L34
![remove-spell-correct](https://user-images.githubusercontent.com/40356749/122746311-d8f09300-d2c4-11eb-817a-a7de338083e7.png)

- [ ] add `Send from` account selection section (which lists the current user's loaded accounts) and `Send to` account input section (string input) for the `Transfer <Token>` modal https://github.com/PlasmNetwork/plasm-apps-vue/blob/9723ad6386e0a6d1d170b5ac4490424c41cea4b4/src/components/balance/ModalTransferAmount.vue#L35
![add-send-from-send-to](https://user-images.githubusercontent.com/40356749/122746525-0e957c00-d2c5-11eb-9f27-cd39a23c3abb.png)
