### ISSUE TITLE
Add network connection indicator and injected extension handling

### ISSUE THREAD

**Issue by hoonsubin** [PlasmNetwork/plasm-apps-vue#31]
# Task Summary

We want to change the style for the network connection component and handling browser injections from extension wallets.

The client app should show a stylized spinner when initializing the application. After the application has been loaded (and connected to the chain), there should be an indicator for the API connection status.
We need a chain metadata upload feature for browser extensions to register Plasm Network chain metadata.

# Task List

- [x] change the initial network connection spinner style to be an overlay of the main page instead of a white blank page when opening the page for the first time https://github.com/PlasmNetwork/plasm-apps-vue/blob/9d0538083fe77423370fdec5351de34e010047c4/src/App.vue#L11 https://github.com/PlasmNetwork/plasm-apps-vue/blob/9d0538083fe77423370fdec5351de34e010047c4/src/components/common/ModalLoading.vue#L7

- [x] add network connection status indicator (a colored dot) to the side of the main logo in the sidebar. Green for connected, pulsing orange for connecting, red when the client is offline https://github.com/PlasmNetwork/plasm-apps-vue/blob/c99b29f290bf2b3be6dd96a886fb112a0aa52a19/src/components/common/SidebarCommon.vue#L3
![add-connection-status](https://user-images.githubusercontent.com/40356749/122748562-4e5d6300-d2c7-11eb-841a-a3d6c0b80545.png)

- [ ] show a popup that asks the user to install polkadot-js extension if no account was loaded from the client ([firefox](https://addons.mozilla.org/en-US/firefox/addon/polkadot-js-extension/), [chrome](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd)) https://github.com/PlasmNetwork/plasm-apps-vue/blob/9723ad6386e0a6d1d170b5ac4490424c41cea4b4/src/api/polkadot/connectApi.ts#L24
![show-popup-when-no-account](https://user-images.githubusercontent.com/40356749/122748667-7056e580-d2c7-11eb-91ef-aff720208060.png)
