### ISSUE TITLE
Improve ink smart contract instantiation and code hash metadata upload feature

### ISSUE THREAD

**Issue by hoonsubin** [PlasmNetwork/plasm-apps-vue#32]
# Task Summary

Currently, we cannot provide any arguments for the contract `constructor` method from the `ModalCreateDapps.vue` component. We should allow the user to pass the arguments (even if it's just in raw string input that is converted inside the app) when instantiating a new contract.
Additionally, when we want to add a contract from a code hash, we need to provide the `metadata.json` (ABI) file for it. Right now it only accepts raw string input, but let's improve this so that the user can upload the `json` file directly.

# Task List

- [x] allow users to input contract constructor arguments when instantiating a new contract (the `new` method) https://github.com/PlasmNetwork/plasm-apps-vue/blob/45381bafb72eabba103bff0cae0b12a9dba092c2/src/components/dapps/ModalCreateDapps.vue#L288
![add-constructor-args](https://user-images.githubusercontent.com/40356749/122751058-3f2be480-d2ca-11eb-8b17-25fa85a6135e.png)

- [ ] allow users to pass arguments for contract methods or fetch contract stores. We may want to create a contract modal that renders all interactable messages if we want this feature to be extendible. If this task takes too long, we'll separate this into its own issue and skip this one for the initial launch.

- [x] change the balance input component format for `Endowment (UNIT)` and `Max gas allowed` so that it matches the style of ones in the `Transfer <Token>` [modal](https://github.com/PlasmNetwork/plasm-apps-vue/blob/9723ad6386e0a6d1d170b5ac4490424c41cea4b4/src/components/balance/ModalTransferAmount.vue#L110). The input box should allow the users to choose a different token metric or use decimal strings https://github.com/PlasmNetwork/plasm-apps-vue/blob/45381bafb72eabba103bff0cae0b12a9dba092c2/src/components/dapps/ModalCreateDapps.vue#L140
![change-balance-input-format](https://user-images.githubusercontent.com/40356749/122753665-8c5d8580-d2cd-11eb-892d-b12508a868ae.png)

- [x] allow the user to upload the `metadata.json` file instead of pasting the full JSON string when adding a contract code hash and switch the location for the bundle name and code hash input box https://github.com/PlasmNetwork/plasm-apps-vue/blob/45381bafb72eabba103bff0cae0b12a9dba092c2/src/components/dapps/ModalCodeHash.vue#L55
![add-upload-abi](https://user-images.githubusercontent.com/40356749/122751269-8023f900-d2ca-11eb-9e75-2d5f40c04167.png)

**Comment by sirius651** [comment]
@LRUki can I tackle these 2 tasks if you're busy to working on params thing? : 
`allow the user to upload the metadata.json file instead of pasting the full JSON string when adding a contract code hash and switch the location for the bundle name and code hash input box`

`change the balance input component format for Endowment (UNIT) and Max gas allowed so that it matches the style of ones in the Transfer <Token> modal. The input box should allow the users to choose a different token metric or use decimal strings`

**Comment by sirius651** [comment]
The two tasks below have been completed. do I know what's the current status about first task? @LRUki @hoonsubin

**Comment by hoonsubin** [comment]
@sirius651 from what I know, @LRUki is currently working on the input formatting but not the message sending logic yet. What is your estimate for implementing it? If it's not too difficult, I think you can go ahead with the implementation.

**Comment by sirius651** [comment]
@hoonsubin alright, I'll hop on that after resolving PR #43
