### ISSUE TITLE
Change the layout of the contract item component and add contract message sending feature

### ISSUE THREAD

**Issue by hoonsubin** [PlasmNetwork/plasm-apps-vue#33]
# Task Summary

Change the `ContractItem.vue` component layout so it is more intuitive for the user. Add intractability to the contract (sign & send contract message, fetch contract store value).

# Task List

- [x] remove the `Code bundle name` section since it is already rendered above the contract address. Make the copy icon size consistent https://github.com/PlasmNetwork/plasm-apps-vue/blob/45381bafb72eabba103bff0cae0b12a9dba092c2/src/components/dapps/ContractItem.vue#L87
![remove-code-bundle-name](https://user-images.githubusercontent.com/40356749/122752174-941c2a80-d2cb-11eb-8765-56c1e74a4213.png)

- [x] add a `export ABI` (or `download metadata`) button that lets the user download the `metadata.json` file from the contract item, instead of displaying the `json` string https://github.com/PlasmNetwork/plasm-apps-vue/blob/45381bafb72eabba103bff0cae0b12a9dba092c2/src/components/dapps/ContractItem.vue#L95
![add-abi-download](https://user-images.githubusercontent.com/40356749/122752272-b150f900-d2cb-11eb-96ab-6279c5657324.png)

- [x] display contract methods and stores in the contract item. We will need to fix the contract message component and abi hook to work on this https://github.com/PlasmNetwork/plasm-apps-vue/blob/45381bafb72eabba103bff0cae0b12a9dba092c2/src/components/dapps/ContractInfo.vue#L25
![list-contract-methods](https://user-images.githubusercontent.com/40356749/122752484-fd03a280-d2cb-11eb-92b3-10bfc6badfbb.png)
