### ISSUE TITLE
005-Implement Base Provider Component for API injection

### ISSUE THREAD

**Issue by satellitex** [PlasmNetwork/plasm-apps-vue#8]
# Task Summary

Implement the polkadot api provider component that allows dependency injection, hooks, and provider context to be accessed from other components using the Composition API.

## Subtasks

This ticket will be considered as finished when the following items are fulfilled:

- [ ] setup a basic asynchronous provider parent component
- [ ] create a basic state management logic and event hooks that are accessible from other components within the context
- [ ] add loading screen + error handling
- [ ] implement basic polkadot API hook
- [ ] simple display of Substrate account node balance

## Dependencies

https://github.com/PlasmNetwork/plasm-apps-vue/issues/2

## Difficulty

6/10

## Estimated Implementation Time

> Note: the task start date is considered to be the day the ticket was opened or the next day when the dependent task was closed

- **Optimistic**: 5 days
- **Normal**: 10 days
- **Pessimistic**: 2 weeks
